on:
  workflow_dispatch:

name: velero testing 
env:
  PYTHON_VERSION: 3.9

jobs:
  k8s-verify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: set up velero
        id: setup-velero
        run:
          curl -o /tmp/velero.tar.gz https://github.com/vmware-tanzu/velero/releases/download/v1.5.1/velero-v1.5.1-linux-amd64.tar.gz 
          tar -C /tmp -xvf /tmp/velero.tar.gz
          mv /tmp/velero-v1.5.1-linux-amd64/velero /usr/local/bin/velero
          chmod +x /usr/local/bin/velero
          velero --help
          which velero
          
